// <auto-generated />
using System;
using LongJobProcessor.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LongJobProcessor.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LongJobProcessor.Domain.Entities.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Jobs");

                    b.HasDiscriminator<string>("JobType").HasValue("Job");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LongJobProcessor.Domain.Entities.Jobs.InputEncode.InputEncodeJob", b =>
                {
                    b.HasBaseType("LongJobProcessor.Domain.Entities.Jobs.Job");

                    b.Property<int>("Cursor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Produced")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.HasDiscriminator().HasValue("InputEncode");
                });

            modelBuilder.Entity("LongJobProcessor.Domain.Entities.Jobs.Job", b =>
                {
                    b.OwnsOne("LongJobProcessor.Domain.StateMachine.JobStateMachine", "State", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uuid");

                            b1.Property<string>("JobOwner")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("JobOwner");

                            b1.Property<int>("RetryCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("RetryCount");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("Status");

                            b1.Property<DateTimeOffset?>("TakenUntil")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("TakenUntil");

                            b1.HasKey("JobId");

                            b1.ToTable("Jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("State")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
